require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'ChallengeIt' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])
  permissions_path = '../node_modules/react-native-permissions/ios'
  pod 'Permission-Camera', :path => "#{permissions_path}/Camera.podspec"
  pod 'Permission-LocationWhenInUse', :path => "#{permissions_path}/LocationWhenInUse.podspec"
  pod 'Permission-MediaLibrary', :path => "#{permissions_path}/MediaLibrary.podspec"
  pod 'Permission-Microphone', :path => "#{permissions_path}/Microphone.podspec"
  pod 'Permission-PhotoLibrary', :path => "#{permissions_path}/PhotoLibrary.podspec"
  pod 'GoogleSignIn', '~> 5.0.2'
  pod 'RNShare', :path => '../node_modules/react-native-share'

  pod 'RNImageCropPicker', :path => '../node_modules/react-native-image-crop-picker'
  pod 'RNSnackbar', :path => '../node_modules/react-native-snackbar'

  pod 'RNFS', :path => '../node_modules/react-native-fs'

  pod 'RNSoundPlayer', :path => '../node_modules/react-native-sound-player'

  target 'ChallengeItTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'ChallengeIt-tvOS' do
  # Pods for ChallengeIt-tvOS

  target 'ChallengeIt-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
